"use client";

import { FormEvent, KeyboardEvent, useEffect, useRef, useState } from "react";

type Language = "es" | "en";
type MessageRole = "user" | "assistant";

type ChatMessage = {
  id: string;
  role: MessageRole;
  text: string;
  source?: "gemini" | "demo";
};

type IconName =
  | "book"
  | "chat"
  | "chevron"
  | "globe"
  | "heart"
  | "info"
  | "menu"
  | "plus"
  | "send"
  | "sparkle"
  | "target"
  | "users";

const copy = {
  es: {
    context: "Conversación",
    active: "IA educativa activa",
    help: "Sobre Equa",
    newChat: "Nueva conversación",
    explore: "Explorar",
    conversation: "Mi conversación",
    resources: "Recursos",
    about: "Sobre Equa",
    topics: "Temas frecuentes",
    topicHistory: "Historia y movimientos",
    topicWork: "Trabajo y cuidados",
    topicCountries: "Brechas por país",
    languageLabel: "Idioma de respuesta",
    languageValue: "Español",
    userName: "Invitado",
    eyebrow: "Un espacio para entender y actuar",
    titleStart: "Entender la igualdad",
    titleEnd: "cambia todo.",
    intro:
      "Pregunta con confianza. Equa convierte conceptos complejos en conversaciones claras, humanas y con contexto.",
    chatTitle: "Tu espacio de preguntas",
    chatLanguage: "Respuestas en español",
    exploreTopic: "Explora un tema",
    placeholder: "Escribe tu pregunta sobre igualdad de género...",
    disclaimer: "Equa es una guía educativa. Para cifras actuales, revisa siempre la fuente y el año.",
    impactTitle: "Áreas que podemos explorar",
    impactSubtitle: "Mapa de conversación",
    rights: "Derechos",
    education: "Educación",
    work: "Trabajo",
    rightsValue: "100%",
    educationValue: "80%",
    workValue: "65%",
    factTitle: "Dato para llevar",
    fact:
      "La igualdad de género no es solo un tema de mujeres: es una condición para sociedades más justas, seguras y prósperas.",
    sourceLink: "Ver recursos",
    sourceLabel: "Respuesta generada por Gemini",
    demoLabel: "Respuesta de demostración",
    error:
      "No pude conectarme ahora. Puedes volver a intentarlo o explorar una de las preguntas sugeridas.",
  },
  en: {
    context: "Conversation",
    active: "Educational AI active",
    help: "About Equa",
    newChat: "New conversation",
    explore: "Explore",
    conversation: "My conversation",
    resources: "Resources",
    about: "About Equa",
    topics: "Popular topics",
    topicHistory: "History & movements",
    topicWork: "Work & care",
    topicCountries: "Gaps by country",
    languageLabel: "Response language",
    languageValue: "English",
    userName: "Guest",
    eyebrow: "A space to understand and act",
    titleStart: "Understanding equality",
    titleEnd: "changes everything.",
    intro:
      "Ask with confidence. Equa turns complex ideas into clear, human conversations with context.",
    chatTitle: "Your question space",
    chatLanguage: "Answers in English",
    exploreTopic: "Explore a topic",
    placeholder: "Write your question about gender equality...",
    disclaimer: "Equa is an educational guide. For current figures, always check the source and year.",
    impactTitle: "Areas we can explore",
    impactSubtitle: "Conversation map",
    rights: "Rights",
    education: "Education",
    work: "Work",
    rightsValue: "100%",
    educationValue: "80%",
    workValue: "65%",
    factTitle: "Takeaway",
    fact:
      "Gender equality is not only a women’s issue: it is a foundation for fairer, safer and more prosperous societies.",
    sourceLink: "View resources",
    sourceLabel: "Response generated by Gemini",
    demoLabel: "Demo response",
    error: "I could not connect right now. Try again or explore one of the suggested questions.",
  },
};

const prompts = {
  es: [
    { icon: "book" as IconName, label: "¿Cuántos años lleva esta lucha?" },
    { icon: "target" as IconName, label: "¿Dónde es más grande la brecha?" },
    { icon: "users" as IconName, label: "¿Qué significa igualdad de género?" },
  ],
  en: [
    { icon: "book" as IconName, label: "How long has this movement existed?" },
    { icon: "target" as IconName, label: "Where is the gap the widest?" },
    { icon: "users" as IconName, label: "What does gender equality mean?" },
  ],
};

function welcomeMessage(language: Language): ChatMessage {
  return {
    id: "welcome",
    role: "assistant",
    text:
      language === "es"
        ? "Hola, soy Equa. Estoy aquí para ayudarte a entender la igualdad de género desde la historia, los datos y la vida cotidiana. ¿Por dónde empezamos?"
        : "Hi, I’m Equa. I’m here to help you understand gender equality through history, data and everyday life. Where should we begin?",
    source: "demo",
  };
}

function Icon({ name, size = 16 }: { name: IconName; size?: number }) {
  const common = {
    width: size,
    height: size,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.8,
    strokeLinecap: "round" as const,
    strokeLinejoin: "round" as const,
    "aria-hidden": true,
  };

  if (name === "book") {
    return <svg {...common}><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15H6.5A2.5 2.5 0 0 0 4 20.5v-15Z" /><path d="M4 20.5A2.5 2.5 0 0 1 6.5 18H20M8 7h8M8 11h6" /></svg>;
  }
  if (name === "chat") {
    return <svg {...common}><path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8.3 8.3 0 0 1-3.6-.8L4 20l1.8-3.7A7.2 7.2 0 0 1 4 11.5 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z" /><path d="M8 11.5h.01M12 11.5h.01M16 11.5h.01" strokeWidth="2.6" /></svg>;
  }
  if (name === "chevron") {
    return <svg {...common}><path d="m7 10 5 5 5-5" /></svg>;
  }
  if (name === "globe") {
    return <svg {...common}><circle cx="12" cy="12" r="8.5" /><path d="M3.8 9h16.4M3.8 15h16.4M12 3.5c2 2.3 3 5.1 3 8.5s-1 6.2-3 8.5c-2-2.3-3-5.1-3-8.5s1-6.2 3-8.5Z" /></svg>;
  }
  if (name === "heart") {
    return <svg {...common}><path d="M20.8 8.8c0 5.1-8.8 10.1-8.8 10.1S3.2 13.9 3.2 8.8A4.8 4.8 0 0 1 12 6.1a4.8 4.8 0 0 1 8.8 2.7Z" /></svg>;
  }
  if (name === "info") {
    return <svg {...common}><circle cx="12" cy="12" r="8.5" /><path d="M12 10.8v5M12 7.8h.01" strokeWidth="2.3" /></svg>;
  }
  if (name === "menu") {
    return <svg {...common}><path d="M4 7h16M4 12h16M4 17h16" /></svg>;
  }
  if (name === "plus") {
    return <svg {...common}><path d="M12 5v14M5 12h14" /></svg>;
  }
  if (name === "send") {
    return <svg {...common}><path d="m21 3-7.2 18-3.2-7.6L3 10.2 21 3Z" /><path d="M10.6 13.4 21 3" /></svg>;
  }
  if (name === "sparkle") {
    return <svg {...common}><path d="m12 3-1.2 5.8L5 10l5.8 1.2L12 17l1.2-5.8L19 10l-5.8-1.2L12 3ZM19 15l-.5 2.5L16 18l2.5.5L19 21l.5-2.5L22 18l-2.5-.5L19 15Z" /></svg>;
  }
  if (name === "target") {
    return <svg {...common}><circle cx="12" cy="12" r="8.5" /><circle cx="12" cy="12" r="4.5" /><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none" /></svg>;
  }
  return <svg {...common}><path d="M16 20v-1.5a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4V20M9.5 10.5A3.5 3.5 0 1 0 9.5 3a3.5 3.5 0 0 0 0 7.5ZM17 11a3 3 0 1 0 0-6M20.5 20v-1.5a4 4 0 0 0-3-3.8" /></svg>;
}

export function EquityChat() {
  const [language, setLanguage] = useState<Language>("es");
  const [messages, setMessages] = useState<ChatMessage[]>([welcomeMessage("es")]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const t = copy[language];

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [messages, isLoading]);

  function changeLanguage(nextLanguage: Language) {
    setLanguage(nextLanguage);
    setMessages((current) =>
      current.length === 1 && current[0].id === "welcome"
        ? [welcomeMessage(nextLanguage)]
        : current,
    );
    setSidebarOpen(false);
  }

  function newConversation() {
    setMessages([welcomeMessage(language)]);
    setInput("");
    setSidebarOpen(false);
  }

  async function submitMessage(rawMessage: string) {
    const message = rawMessage.trim();
    if (!message || isLoading) return;

    const history = messages.filter((item) => item.id !== "welcome");
    const userMessage: ChatMessage = {
      id: `${Date.now()}-user`,
      role: "user",
      text: message,
    };

    setMessages((current) => [...current, userMessage]);
    setInput("");
    setIsLoading(true);

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message, language, history, modelMode: "auto" }),
      });
      const data = (await response.json()) as { answer?: string; source?: "gemini" | "demo"; model?: string };

      if (!response.ok || !data.answer) throw new Error("chat_request_failed");

      setMessages((current) => [
        ...current,
        {
          id: `${Date.now()}-assistant`,
          role: "assistant",
          text: data.answer ?? t.error,
          source: data.source ?? "demo",
        },
      ]);
    } catch {
      setMessages((current) => [
        ...current,
        {
          id: `${Date.now()}-error`,
          role: "assistant",
          text: t.error,
          source: "demo",
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    void submitMessage(input);
  }

  function handleKeyDown(event: KeyboardEvent<HTMLTextAreaElement>) {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      void submitMessage(input);
    }
  }

  return (
    <div className="app-shell">
      {sidebarOpen && <button className="mobile-overlay" aria-label="Cerrar menú" onClick={() => setSidebarOpen(false)} />}
      <aside className={`sidebar ${sidebarOpen ? "open" : ""}`}>
        <div className="brand"><span className="brand-mark"><Icon name="sparkle" size={16} /></span>Equa<span className="brand-dot">.</span></div>
        <button className="new-chat" onClick={newConversation}><Icon name="plus" size={15} />{t.newChat}</button>

        <nav className="sidebar-nav" aria-label={t.explore}>
          <span className="nav-caption">{t.explore}</span>
          <button className="nav-link active" onClick={newConversation}><Icon name="chat" size={16} />{t.conversation}</button>
          <a className="nav-link" href="#impacto" onClick={() => setSidebarOpen(false)}><Icon name="book" size={16} />{t.resources}</a>
          <a className="nav-link" href="#sobre" onClick={() => setSidebarOpen(false)}><Icon name="info" size={16} />{t.about}</a>
        </nav>

        <div className="sidebar-topics">
          <span className="nav-caption">{t.topics}</span>
          <button className="sidebar-topic" onClick={() => void submitMessage(prompts[language][0].label)}><span>{t.topicHistory}</span><span>01</span></button>
          <button className="sidebar-topic" onClick={() => void submitMessage(prompts[language][1].label)}><span>{t.topicWork}</span><span>02</span></button>
          <button className="sidebar-topic" onClick={() => void submitMessage(prompts[language][2].label)}><span>{t.topicCountries}</span><span>03</span></button>
        </div>

        <div className="sidebar-bottom">
          <div className="language-card">
            <Icon name="globe" size={16} />
            <div className="language-copy"><span className="language-label">{t.languageLabel}</span><span className="language-value">{t.languageValue}</span></div>
            <div className="language-toggle" role="group" aria-label={t.languageLabel}>
              <button className={language === "es" ? "active" : ""} onClick={() => changeLanguage("es")}>ES</button>
              <button className={language === "en" ? "active" : ""} onClick={() => changeLanguage("en")}>EN</button>
            </div>
          </div>
          <div className="profile-row"><span className="profile-avatar">{language === "es" ? "TÚ" : "YOU"}</span>{t.userName}</div>
        </div>
      </aside>

      <main className="main-content">
        <header className="topbar">
          <div className="topbar-context"><button className="mobile-menu" aria-label="Abrir menú" onClick={() => setSidebarOpen(true)}><Icon name="menu" size={17} /></button><span>Equa</span><span className="topbar-separator">/</span><strong>{t.context}</strong></div>
          <div className="topbar-right"><span className="ai-status"><i className="status-dot" />{t.active}</span><button className="topbar-help" onClick={() => document.getElementById("sobre")?.scrollIntoView()}><Icon name="info" size={14} />{t.help}</button></div>
        </header>

        <div className="content-wrap">
          <section className="intro-row" aria-labelledby="page-title">
            <div><div className="eyebrow"><span className="eyebrow-line" />{t.eyebrow}</div><h1 id="page-title" className="hero-title">{t.titleStart}<br /><em>{t.titleEnd}</em></h1><p className="hero-copy">{t.intro}</p></div>
            <div className="hero-mark" aria-hidden="true"><Icon name="heart" size={52} /></div>
          </section>

          <div className="workspace-grid">
            <section className="chat-card" aria-label={t.chatTitle}>
              <div className="chat-card-header"><div className="chat-card-title"><span className="chat-card-title-icon"><Icon name="sparkle" size={14} /></span>{t.chatTitle}</div><span className="chat-card-language">{t.chatLanguage}</span></div>
              <div className="messages" aria-live="polite">
                {messages.map((message) => (
                  <div className={`message-row ${message.role}`} key={message.id}>
                    <span className={`message-avatar ${message.role === "user" ? "user-avatar" : ""}`}>{message.role === "user" ? (language === "es" ? "TÚ" : "YOU") : <Icon name="sparkle" size={15} />}</span>
                    <div className="message-body"><div className="message-meta"><span>{message.role === "user" ? (language === "es" ? "Tú" : "You") : "Equa"}</span><span>·</span><span>{language === "es" ? "ahora" : "now"}</span></div><div className="message-bubble">{message.text}</div>{message.role === "assistant" && message.id !== "welcome" && <span className="message-source">{message.source === "gemini" ? t.sourceLabel : t.demoLabel}</span>}</div>
                  </div>
                ))}
                {isLoading && <div className="message-row"><span className="message-avatar"><Icon name="sparkle" size={15} /></span><div className="message-body"><div className="message-meta"><span>Equa</span><span>·</span><span>{language === "es" ? "pensando" : "thinking"}</span></div><div className="message-bubble"><span className="typing-dots"><i /><i /><i /></span></div></div></div>}
                <div ref={messagesEndRef} />
              </div>

              <div className="quick-prompts"><span className="quick-prompts-label">{t.exploreTopic}</span><div className="prompt-grid">{prompts[language].map((prompt) => <button className="prompt-chip" key={prompt.label} onClick={() => void submitMessage(prompt.label)}><Icon name={prompt.icon} size={14} />{prompt.label}</button>)}</div></div>
              <form className="composer" onSubmit={handleSubmit}><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={handleKeyDown} placeholder={t.placeholder} aria-label={t.placeholder} rows={1} /><button className="send-button" type="submit" disabled={isLoading || !input.trim()} aria-label={language === "es" ? "Enviar pregunta" : "Send question"}><Icon name="send" size={16} /></button></form>
              <p className="disclaimer">{t.disclaimer}</p>
            </section>

            <aside className="insights-panel" id="impacto" aria-label={t.impactTitle}>
              <div className="panel-heading"><h2>{t.impactTitle}</h2><span>{t.impactSubtitle}</span></div>
              <div className="stat-grid"><div className="stat-card"><span className="stat-value">1945</span><p>{language === "es" ? "La igualdad se reconoce como derecho en la Carta de la ONU." : "Equality is recognized as a right in the UN Charter."}</p></div><div className="stat-card"><span className="stat-value">ODS 5</span><p>{language === "es" ? "Un objetivo global: lograr la igualdad y empoderar." : "A global goal: achieve equality and empower all."}</p></div><div className="stat-card"><span className="stat-value">∞</span><p>{language === "es" ? "La conversación sigue: cada generación puede ampliar el camino." : "The conversation continues: every generation can widen the path."}</p></div></div>
              <div className="impact-card"><div className="impact-title"><Icon name="target" size={15} />{t.impactTitle}</div><div className="impact-list"><div className="impact-row"><span>{t.rights}</span><span className="impact-track"><i style={{ width: "100%" }} /></span><strong>{t.rightsValue}</strong></div><div className="impact-row"><span>{t.education}</span><span className="impact-track"><i style={{ width: "80%" }} /></span><strong>{t.educationValue}</strong></div><div className="impact-row"><span>{t.work}</span><span className="impact-track"><i style={{ width: "65%" }} /></span><strong>{t.workValue}</strong></div></div></div>
              <div className="resource-card" id="sobre"><div className="impact-title"><Icon name="heart" size={15} />{t.factTitle}</div><p>{t.fact}</p><a href={language === "es" ? "https://www.unwomen.org/es" : "https://www.unwomen.org/en"} target="_blank" rel="noreferrer">{t.sourceLink}<Icon name="chevron" size={13} /></a></div>
            </aside>
          </div>
        </div>
      </main>
    </div>
  );
}
